version: '3'

services:
  server:
    container_name: server
    build: ./server
    ports:
      - "8080:90"
    volumes:
      - ./server:/app
  user_api:
    build: users_api/
    ports:
      - "8000:80"
    volumes:
      - ./users_api:/app